- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: present  

- name: Disable default site
  become: yes
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent

- name: Setup site
  become: yes
  template:
    src: host.conf.j2
    dest: "/etc/nginx/sites-available/{{ nginx_servername }}.conf"
    mode: 0644

- name: Create symbolic link
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ nginx_servername }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ nginx_servername }}.conf"
    state: link
  notify: Restart nginx

- name: Add the user www-data to {{ rvm_user }} group
  become: yes
  user:
    name: www-data
    shell: /bin/bash
    groups: "{{ rvm_user }}"
    append: yes


