- name: Allow HTTP, HTTPS, DNS and SSH
  become: yes
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    jump: ACCEPT
  loop:
    - 22
    - 53
    - 80
    - 443
    
- name: Drop connections rule
  become: yes
  iptables:
    chain: INPUT
    jump: DROP
