---
# tasks file for installing mariadb
- name: Install required packages for mariadb
  become: yes
  apt:
    name: software-properties-common, mariadb-client, python3-pip
    update_cache: yes

- name: Install pymysql
  become: yes
  pip:
    name: pymysql
    state: present

- name: Set .my.cnf file
  become: yes
  template: 
    src: my.cnf.j2 
    dest: /root/.my.cnf 
    mode: 0600
    
- name: Create database with name 'redmine'
  become: yes
  community.mysql.mysql_db:
    name: redmine
    encoding: utf8
    state: present

- name: Create user for redmine db
  become: yes
  community.mysql.mysql_user:
    name: redmine
    password: "{{mariadb_redmine_password}}"
    priv: 'redmine.*:ALL'
    state: present
    
