- name: download
  become: yes
  get_url:
    url: "{{ redmine_url }}/redmine-{{ redmine_version }}.zip"
    dest: "/tmp/redmine-{{ redmine_version }}.zip"

- name: Remove destination if exists
  become: yes
  file:
    state: absent
    path: "{{ redmine_project_dir }}"

- name: Extract
  become: yes
  shell: "unzip /tmp/redmine-{{ redmine_version }}.zip -d /tmp/redmine-{{ redmine_version }}"

- name: Rename folder
  become: yes
  command: "mv /tmp/redmine-{{ redmine_version }} {{ redmine_project_dir }}"

- name: Change owner to {{ rvm_user }}
  become: yes
  file:
    dest: "{{ redmine_project_dir }}"
    owner: "{{ rvm_user }}"
    group: "{{ rvm_group }}"
    recurse: yes

- name: Install dependencies
  remote_user: "{{ rvm_user }}"
  become: yes
  community.general.bundler:
    state: present
    gemfile: "{{ redmine_project_dir }}/Gemfile"

- name: Install mysql2 gem
  remote_user: "{{ rvm_user }}"
  become: yes
  community.general.gem:
    name: mysql2
    state: latest

- name: Copy database config
  remote_user: "{{ rvm_user }}"
  become: yes
  template:
    src: database.yml.j2
    dest: "{{ redmine_project_dir }}/config/database.yml"
    mode: 0644

- name: create configuration.yml
  remote_user: "{{ rvm_user }}"
  become: yes
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_project_dir }}/config/configuration.yml"
    mode: 0644
  when: redmine_email is defined

- name: Generate secret token
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "rake generate_secret_token"
  args:
    chdir: "{{ redmine_project_dir }}"

- name: Migrate Databases
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "bundle exec rake db:migrate RAILS_ENV=production"
  args:
    chdir: "{{ redmine_project_dir }}"

- name: Generate default config
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en"
  args:
    chdir: "{{ redmine_project_dir }}"