---
# tasks file for puma

- name: install puma
  community.general.gem:
    name: puma
    state: present
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Create socket and pid directories
  remote_user: "{{ rvm_user }}"
  become: yes
  file:
    path: "{{ redmine_project_dir }}/redmine/{{ item }}"
    state: directory
    owner: "{{ rvm_user }}"
    group: redmine
    mode: 0644
  loop:
    - sockets
    - pids

- name: Set service file
  become: yes
  template: 
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    force: yes
    owner: "{{ rvm_user }}"
    mode: 0644

- name: Set service file
  remote_user: "{{ rvm_user }}"
  become: yes
  template: 
    src: puma.rb.j2
    dest: "{{ redmine_project_dir }}/redmine/config/puma.rb"
    mode: 0644

- name: Enable puma
  become: yes
  service:
    name: puma
    enabled: yes

- name: Restart puma
  become: yes
  service:
    name: puma
    state: restarted