---
# tasks file for puma
- name: Install puma gem
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} gem install puma"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
    
- name: Create socket and pid directories
  remote_user: "{{ rvm_user }}"
  become: yes
  file:
    path: "{{ redmine_project_dir }}/redmine/{{ item }}"
    state: directory
    owner: "{{ rvm_user }}"
    group: redmine
    mode: 0755
  loop:
    - sockets
    - pids

- name: Set service file
  become: yes
  template: 
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    force: yes
    owner: "{{ rvm_user }}"
    mode: 0644
  notify: Restart puma

- name: Set service file
  remote_user: "{{ rvm_user }}"
  become: yes
  template: 
    src: puma.rb.j2
    dest: "{{ redmine_project_dir }}/redmine/config/puma.rb"
    mode: 0644
  notify: Restart puma


