---
- name: Install bundler
  community.general.gem:
    name: bundler
    state: present
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Install dependencies
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "/home/{{ rvm_user }}/.rvm/bin/rvm-exec 2.6.6 bundle install "
  args:
    chdir: "{{ redmine_project_dir }}/redmine"

- name: Install mysql2 gem
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "/home/{{ rvm_user }}/.rvm/bin/rvm-exec 2.6.6 gem install mysql2"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"

- name: Copy database config
  remote_user: "{{ rvm_user }}"
  become: yes
  template:
    src: database.yml.j2
    dest: "{{ redmine_project_dir }}/redmine/config/database.yml"
    mode: 0644

- name: Create configuration.yml
  remote_user: "{{ rvm_user }}"
  become: yes
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_project_dir }}/redmine/config/configuration.yml"
    mode: 0644
  when: redmine_email is defined

- name: Generate secret token
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "rake generate_secret_token"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Migrate Databases
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "bundle exec rake db:migrate RAILS_ENV=production"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Generate default config
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
