---
# tasks file for redmine dependencies
- name: Install bundler gem
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} gem install bundler"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
    
- name: Install mysql2 gem
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} gem install mysql2"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Install redmine dependencies
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} bundle install"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
    
- name: Copy database config
  become_user: "{{ rvm_user }}"
  become: yes
  template:
    src: database.yml.j2
    dest: "{{ redmine_project_dir }}/redmine/config/database.yml"
    mode: 0644

- name: Create configuration.yml
  become_user: "{{ rvm_user }}"
  become: yes
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_project_dir }}/redmine/config/configuration.yml"
    mode: 0644
  when: redmine_email is defined

- name: Generate secret token
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} bundle exec rake generate_secret_token"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
    
- name: Migrate Databases
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} bundle exec rake db:migrate RAILS_ENV=production"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Generate default config
  become_user: "{{ rvm_user }}"
  become: yes
  shell: "rvm-exec {{ rvm_ruby_version }} bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
