---
- name: Install unzip
  become: yes
  apt:
    name: 
      - unzip
      - libmariadb-dev
    state: present

- name: Download
  become: yes
  get_url:
    url: "{{ redmine_url }}/redmine-{{ redmine_version }}.zip"
    dest: "/tmp/redmine-{{ redmine_version }}.zip"

- name: Remove destination if exists
  become: yes
  file:
    state: absent
    path: "{{ redmine_project_dir }}/redmine"

- name: Extract
  become: yes
  shell: "unzip /tmp/redmine-{{ redmine_version }}.zip -d {{ redmine_project_dir }}"

- name: Rename folder
  become: yes
  command: mv "{{ redmine_project_dir }}/redmine-{{ redmine_version }}" "{{ redmine_project_dir }}/redmine"

- name: Change owner to {{ rvm_user }}
  become: yes
  file:
    dest: "{{ redmine_project_dir }}/redmine"
    owner: "{{ rvm_user }}"
    group: redmine
    recurse: yes

- name: install bundler
  community.general.gem:
    name: bundler
    state: present
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Install dependencies
  remote_user: "{{ rvm_user }}"
  become: yes
  community.general.bundler:
    state: present
    gemfile: "{{ redmine_project_dir }}/redmine/Gemfile"
    # executable: "/home/{{ rvm_user }}/.rvm/gems/ruby-{{ rvm_ruby_version }}/wrappers/gem"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Install mysql2 gem
  remote_user: "{{ rvm_user }}"
  become: yes
  community.general.gem:
    name: mysql2
    state: latest
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Copy database config
  remote_user: "{{ rvm_user }}"
  become: yes
  template:
    src: database.yml.j2
    dest: "{{ redmine_project_dir }}/redmine/config/database.yml"
    mode: 0644

- name: create configuration.yml
  remote_user: "{{ rvm_user }}"
  become: yes
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_project_dir }}/redmine/config/configuration.yml"
    mode: 0644
  when: redmine_email is defined

- name: Generate secret token
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "rake generate_secret_token"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Migrate Databases
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "bundle exec rake db:migrate RAILS_ENV=production"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Generate default config
  remote_user: "{{ rvm_user }}"
  become: yes
  shell: "bundle exec rake redmine:load_default_data RAILS_ENV=production REDMINE_LANG=en"
  args:
    chdir: "{{ redmine_project_dir }}/redmine"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
