- name: update rbenv repo
  become_user: "{{ rbenv.user }}"
  become: yes
  git: 
    repo: git://github.com/sstephenson/rbenv.git
    dest: "{{ rbenv.root }}"
    version: v1.1.2
  register: git_rbenv

- name: Create (if not exists) ~/.bash.d/
  become_user: "{{ rbenv.user }}"
  become: yes
  file: 
    dest: .bash.d/
    state: directory

- name: Test if rbenv is exported
  become_user: "{{ rbenv.user }}"
  become: yes
  shell: grep -c 'PATH="$HOME/.rbenv/bin:$PATH' .bashrc || true
  register: test_grep

- name: Add rbenv to HOME
  become_user: "{{ rbenv.user }}"
  become: yes
  lineinfile:
    path: .bashrc
    line: export PATH="$HOME/.rbenv/bin:$PATH"
    insertafter: EOF
  when: test_grep.stdout == "0"

- name: Add eval
  become_user: "{{ rbenv.user }}"
  become: yes
  lineinfile:
    path: .bashrc
    line: eval "$(rbenv init -)"
    insertafter: EOF
  when: test_grep.stdout == "0"

- name: add rbenv initialization to profile
  become_user: "{{ rbenv.user }}"
  become: yes
  template: 
    src: templates/rbenv.sh.j2
    dest: .bash.d/50_rbenv.bash
    mode: 0755
  
- name: create temporary directory
  shell: mktemp -d
  register: tempdir

- name: clone ruby-build repo
  git: 
    repo: git://github.com/sstephenson/ruby-build.git
    dest: "{{ tempdir.stdout }}/ruby-build"

- name: install ruby-build
  become: yes
  command: ./install.sh
  args:
    chdir: "{{tempdir.stdout}}/ruby-build"

- name: remove temporary directory
  file:
    path: "{{ tempdir.stdout }}"
    state: absent

- name: "install ruby {{ common.ruby_version }}"
  shell: "{{ rbenv.root }}/bin/rbenv install --skip-existing {{ common.ruby_version }}"

- name: set global ruby {{ common.ruby_version }}
  shell: "{{ rbenv.root }}/bin/rbenv global {{ common.ruby_version }}"

- name: rehash
  shell: "{{ rbenv.root }}/bin/rbenv rehash"
